/* AUTOGENERATED FILE, DO NOT EDIT */
#define CAML_NAME_SPACE
#define _GNU_SOURCE
#include <caml/mlvalues.h>
CAMLprim value caml_eio_eventfd(value);
CAMLprim value caml_eio_mkdirat(value, value, value);
CAMLprim value caml_eio_renameat(value, value, value, value);
CAMLprim value caml_eio_symlinkat(value, value, value);
CAMLprim value caml_eio_getrandom(value, value, value);
CAMLprim value caml_eio_getdents(value);
CAMLprim value caml_eio_clone3(value, value);
CAMLprim value caml_eio_pidfd_send_signal(value, value);
