/* AUTOGENERATED FILE, DO NOT EDIT */
#define CAML_NAME_SPACE
#define _GNU_SOURCE
#include <caml/mlvalues.h>
CAMLprim value caml_eio_posix_send_msg(value, value, value, value, value);
CAMLprim value caml_eio_posix_recv_msg(value, value, value);
CAMLprim value caml_eio_posix_getrandom(value, value, value);
CAMLprim value caml_eio_posix_readv(value, value);
CAMLprim value caml_eio_posix_writev(value, value);
CAMLprim value caml_eio_posix_preadv(value, value, value);
CAMLprim value caml_eio_posix_pwritev(value, value, value);
CAMLprim value caml_eio_posix_openat(value, value, value, value);
CAMLprim value caml_eio_posix_mkdirat(value, value, value);
CAMLprim value caml_eio_posix_unlinkat(value, value, value);
CAMLprim value caml_eio_posix_renameat(value, value, value, value);
CAMLprim value caml_eio_posix_spawn(value, value);
