/* AUTOGENERATED FILE, DO NOT EDIT */
#define CAML_NAME_SPACE
#define _GNU_SOURCE
#include <caml/mlvalues.h>
CAMLprim value eio_unix_make_string_array(value);
CAMLprim value eio_unix_fork_execve(value);
CAMLprim value eio_unix_fork_chdir(value);
CAMLprim value eio_unix_fork_fchdir(value);
CAMLprim value eio_unix_fork_dups(value);
CAMLprim value eio_unix_cap_enter(value);
CAMLprim value eio_unix_readlinkat(value, value, value);
CAMLprim value eio_unix_fchownat(value, value, value, value, value);
CAMLprim value eio_unix_is_blocking(value);
